# Generated by Django 5.0.6 on 2024-06-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buying_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
